---
- name: Gather operating system variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: nginx

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined
  tags: nginx

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' or ansible_os_family == 'AlmaLinux'
  tags: nginx

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: nginx

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags: nginx

- include_tasks: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'
  tags: nginx

- include_tasks: setup-OpenBSD.yml
  when: ansible_os_family == 'OpenBSD'
  tags: nginx

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'
  tags: nginx

- include_tasks: setup-Suse.yml
  when: ansible_os_family == 'Suse'
  tags: nginx

# Vhost configuration.
- import_tasks: vhosts.yml
  tags: nginx

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - Reload nginx
  tags: nginx

- name: Ensure nginx service is running as configured.
  service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
  tags: nginx