---
- name: Import tasks
  tags:
    - dnf-automatic
  block:
    - name: Execute install tasks
      ansible.builtin.import_tasks: 01-install.yml

    - name: Execute config task
      ansible.builtin.import_tasks: 02-config.yml

- name: Enable and start dnf-automatic timer
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: true
    state: started
  tags:
    - dnf-automatic

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - dnf-automatic
