---
- name: Ensure package is installed
  ansible.builtin.package:
    name: dnf-automatic
    state: present
  become: true
  tags: dnf-automatic

- name: Configure service
  ansible.builtin.template:
    src: dnf-automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dnf-automatic
  become: true
  tags: dnf-automatic

- name: Enable and start timer
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: true
    state: started
  become: true
  tags: dnf-automatic

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  become: true
  tags: dnf-automatic
