- name: Restart borgbackup service
  service:
    name: borgbackup
    state: restarted
  when: borgbackup_service_changed

- name: Reload borgbackup configuration
  service:
    name: borgbackup
    state: reloaded
  when: borgbackup_config_changed