---
- name: restart node_exporter
  systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
  become: true
  tags: node_exporter

- name: reload cron
  systemd:
    daemon_reload: true
    name: "textfile-collector-{{ item.src | basename }}.timer"
    state: restarted
  with_items: "{{ node_exporter_textfile_collectors }}"
  become: true
  tags: node_exporter