---
- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  become: true
  tags: postfix-mta

- name: Update aliases
  ansible.builtin.command:
    cmd: newaliases
    creates: /etc/aliases.db
  become: true
  tags: postfix-mta
