---
- name: Copy certificates
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ca_path }}/"
    mode: "0644"
  with_fileglob:
    - "{{ ca_source_path }}"
  register: __ca_copy
  notify: Update truststore
