---
- name: Gather operating system variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - ca

- name: Import tasks
  tags:
    - ca
  block:
    - name: Execute install task
      ansible.builtin.import_tasks: 01-install.yml

    - name: Execute config task
      ansible.builtin.import_tasks: 02-config.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - ca
