---
- name: Import tasks
  tags:
    - auditd
  block:
    - name: Execute install task
      ansible.builtin.import_tasks: 01-install.yml

    - name: Execute config task
      ansible.builtin.import_tasks: 02-config.yml

- name: Ensure service is started and enabled
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true
  tags:
    - auditd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - auditd
