---
- name: Restart nginx
  service:
    name: nginx
    state: restarted
  tags: nginx

- name: Validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false
  tags: nginx

- name: Reload nginx
  service: name=nginx state=reloaded
  when: nginx_service_state == "started"
  tags: nginx