---
- name: Uninstall default time synchronization services
  ansible.builtin.package:
    name: "{{ chrony_uninstall_packages }}"
    state: absent
  when: ansible_os_family == "Debian"

- name: Stop and disable systemd-timesyncd on Debian-based systems
  ansible.builtin.service:
    name: systemd-timesyncd
    state: stopped
    enabled: false
  failed_when: false
  when: ansible_os_family == "Debian"

- name: Ensure package is installed
  ansible.builtin.package:
    name: "{{ chrony_package_name }}"
    state: present
