---
- name: Configure service
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ chrony_config_file }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart chrony

- name: Check current timezone
  ansible.builtin.command:
    cmd: timedatectl show -p Timezone --value
  register: __chrony_current_timezone

- name: Configure timezone if not set
  community.general.timezone:
    name: "{{ chrony_timezone }}"
  when: __chrony_current_timezone.stdout != chrony_timezone

- name: Check if NTP is enabled
  ansible.builtin.command:
    cmd: timedatectl show -p NTP --value
  register: __chrony_ntp_status

- name: Set timedatectl ntp true if not enabled
  ansible.builtin.command:
    cmd: timedatectl set-ntp true
  when: __chrony_ntp_status.stdout != "yes"
