---
- name: Configure firewalld
  ansible.posix.firewalld:
    port: "{{ __chrony_firwall_item }}/udp"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ chrony_port }}"
  loop_control:
    loop_var: __chrony_firwall_item
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | version_compare('7', '>=')

- name: Configure ufw
  community.general.ufw:
    rule: allow
    comment: "Chrony Time"
    port: "{{ __chrony_firwall_item }}"
    proto: udp
    state: enabled
  loop:
    - "{{ chrony_port }}"
  loop_control:
    loop_var: __chrony_firwall_item
  when: ansible_os_family == "Debian" and ansible_distribution_major_version | version_compare('16', '>=')
