---
- name: Update configuration file - fail2ban.local
  ansible.builtin.template:
    src: fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

- name: Update jail configuration file - jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

- name: Create jail configurations
  ansible.builtin.template:
    src: jail.d.j2
    dest: "/etc/fail2ban/jail.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ fail2ban_jails }}"
  when: item.jail_options is defined
  notify: Restart fail2ban

- name: Create filter configurations
  ansible.builtin.template:
    src: filter.d.j2
    dest: "/etc/fail2ban/filter.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ fail2ban_jails }}"
  when: item.filter_options is defined
  notify: Restart fail2ban

- name: Create action configurations
  ansible.builtin.template:
    src: action.local.j2
    dest: "/etc/fail2ban/action.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ fail2ban_jails }}"
  when: item.action_options is defined
  notify: Restart fail2ban
