---
- name: Import tasks
  tags:
    - fail2ban
  block:
    - name: Execute install tasks
      ansible.builtin.import_tasks: 01-install.yml

    - name: Execute config task
      ansible.builtin.import_tasks: 02-config.yml

- name: Ensure service is started and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  tags:
    - fail2ban

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - fail2ban
