---
- name: Firewalld | Combine firewalld_services
  ansible.builtin.set_fact:
    firewalld_services: >-
      {{
        ( firewalld_defaults_services | default([])   ) +
        ( firewalld_group_vars_services | default([]) ) +
        ( firewalld_host_vars_services | default([])  ) +
        ( firewalld_playbook_services | default([])   )
        | unique
      }}
  tags: firewalld

- name: Firewalld | Combine firewalld_zones
  ansible.builtin.set_fact:
    firewalld_zones: >-
      {{
        ( firewalld_defaults_zones | default([])   ) +
        ( firewalld_group_vars_zones | default([]) ) +
        ( firewalld_host_vars_zones | default([])  ) +
        ( firewalld_playbook_zones | default([])   )
        | unique
      }}
  tags: firewalld

- name: Firewalld | Combine firewalld_custom_zones
  ansible.builtin.set_fact:
    firewalld_custom_zones: >-
      {{
        ( firewalld_defaults_custom_zones | default([])   ) +
        ( firewalld_group_vars_custom_zones | default([]) ) +
        ( firewalld_host_vars_custom_zones | default([])  ) +
        ( firewalld_playbook_custom_zones | default([])   )
        | unique
      }}
  tags: firewalld

- name: Firewalld | Combine firewalld_rules
  ansible.builtin.set_fact:
    firewalld_rules: >-
      {{
        ( firewalld_defaults_rules | default([])   ) +
        ( firewalld_group_vars_rules | default([]) ) +
        ( firewalld_host_vars_rules | default([])  ) +
        ( firewalld_playbook_rules | default([])   )
        | unique
      }}
  tags: firewalld


- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'firewall-config'
    - 'firewalld'
    - 'python3-firewall'
  become: true
  tags: firewalld

- name: Define services
  ansible.builtin.template:
    src: "firewalld.service.j2"
    dest: "/etc/firewalld/services/{{ item.service }}.xml"
    mode: '0644'
  # changed_when: false
  register: "_firewalld_define_services"
  loop: "{{ firewalld_services }}"
  loop_control:
    label: "{{ item.service }}"
  when: firewalld_services is defined
  notify: Restart firewalld
  become: true
  tags: firewalld

- name: Start and enable service
  ansible.builtin.service:
    name: "firewalld"
    state: "started"
    enabled: true
  become: true
  tags: firewalld

- name: Manage zones
  ansible.posix.firewalld:
    immediate: "{{ item['immediate'] | default(omit) }}"
    interface: "{{ item['interface'] | default(omit) }}"
    permanent: "{{ item['permanent'] | default(false) }}"
    source: "{{ item['source'] | default(omit) }}"
    state: "{{ item['state'] | default(omit) }}"
    zone: "{{ item['zone'] }}"
  with_items: '{{ firewalld_zones }}'
  when: firewalld_zones is defined
  notify: Reload firewalld
  become: true
  tags: firewalld

- name: Gathering zones
  ansible.builtin.command:
    cmd: "firewall-cmd --get-zones"
  changed_when: false
  register: "_firewalld_get_zones"
  check_mode: false
  when: firewalld_custom_zones is defined
  become: true
  tags: firewalld

- name: Delete custom zones
  ansible.builtin.command:
    cmd: "firewall-cmd --permanent --delete-zone={{ item['zone'] }}"
  register: "_firewalld_custom_zone_deleted"
  with_items: '{{ firewalld_custom_zones }}'
  when: >
        item['zone'] in _firewalld_get_zones['stdout'] and
        not item['present'] and
        firewalld_custom_zones is defined
  notify: Reload firewalld
  become: true
  tags: firewalld

- name: Create custom zones
  ansible.builtin.command:
    cmd: "firewall-cmd --permanent --new-zone {{ item['zone'] }}"
  register: "_firewalld_custom_zone_created"
  with_items: '{{ firewalld_custom_zones }}'
  when: >
        item['zone'] not in _firewalld_get_zones['stdout'] and
        item['present'] and
        firewalld_custom_zones is defined
  notify: Reload firewalld
  become: true
  tags: firewalld

# We need to reload the service when custom zones are create/deleted
- name: Reload service
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  when:
    - _firewalld_define_services is changed
    - firewalld_custom_zones is defined
    - _firewalld_custom_zone_deleted.changed or _firewalld_custom_zone_created.changed
  become: true
  tags: firewalld

- name: Manage rules
  ansible.posix.firewalld:
    immediate: "{{ item['immediate'] | default(omit) }}"
    interface: "{{ item['interface'] | default(omit) }}"
    masquerade: "{{ item['masquerade'] | default(omit) }}"
    permanent: "{{ item['permanent'] | default(omit) }}"
    port: "{{ item['port'] | default(omit) }}"
    service: "{{ item['service'] | default(omit) }}"
    source: "{{ item['source'] | default(omit) }}"
    state: "{{ item['state'] | default(omit) }}"
    zone: "{{ item['zone'] | default(omit) }}"
  with_items: '{{ firewalld_rules }}'
  when: firewalld_rules is defined
  notify: Reload firewalld
  become: true
  tags: firewalld
