---
galaxy_info:
  role_name: ca
  author: Dominik Lenhardt <dominik.lenhardt@inframonks.com>
  company: Inframonks
  description: Manage ca certificates
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  license: MIT
  min_ansible_version: "2.10"

dependencies: []
