---
- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  become: true
  tags: firewalld

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
  become: true
  tags: firewalld
