---
# Automatische Erkennung (kann per host_vars überschrieben werden)
nmcli_default_iface: "{{ ansible_default_ipv4.interface | default('enp6s18') }}"
nmcli_default_gateway: "{{ ansible_default_ipv4.gateway | default(omit) }}"
nmcli_default_address: "{{ ansible_default_ipv4.address | default(omit) }}"
nmcli_default_netmask: "{{ ansible_default_ipv4.netmask | default(omit) }}"
nmcli_default_cidr: "{{ ansible_default_ipv4.network | default(omit) }}"

# Netzwerk Interfaces → können beliebig erweitert werden
nmcli_interfaces:
  - iface: "{{ nmcli_default_iface }}"
    state: up
    type: ethernet
    method4: auto   # DHCP
