---
- name: Create GPG keys directory
  ansible.builtin.file:
    path: /etc/pki/rpm-gpg
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true
  tags: dnf_repos

- name: Download GPG keys
  ansible.builtin.get_url:
    url: "{{ item.gpgkey_url }}"
    dest: "{{ item.gpgkey | regex_replace('file://', '') }}"
    owner: root
    group: root
    mode: '0644'
    timeout: 30
  become: true
  loop: "{{ dnf_repos_list }}"
  when: 
    - dnf_repos_list is defined
    - item.gpgcheck | default('0') | int == 1
    - item.gpgkey_url is defined
    - item.gpgkey is defined
  tags: dnf_repos

- name: Get list of files in /etc/yum.repos.d
  ansible.builtin.command: ls /etc/yum.repos.d
  register: __dnf_repos_files
  tags: dnf_repos

- name: Remove original repos if configured
  ansible.builtin.file:
    path: /etc/yum.repos.d/{{ item }}
    state: absent
  become: true
  loop: "{{ __dnf_repos_files.stdout_lines }}"
  when: dnf_repos_remove_original and item not in ['local.repo']
  tags: dnf_repos

- name: Configure DNF repositories
  ansible.builtin.template:
    src: local.repo.j2
    dest: /etc/yum.repos.d/local.repo
    owner: root
    group: root
    mode: '0644'
  become: true
  when: dnf_repos_list is defined and dnf_repos_list | length > 0
  tags: dnf_repos
