---
- name: Configure /etc/hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: true
  tags: hosts

- name: Configure /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"
  become: true
  tags: hosts
