- name: Combine lvm_config
  ansible.builtin.set_fact:
    lvm_config: >-
      {{
        (lvm_defaults_config | default([])) +
        (lvm_group_vars_config | default([])) +
        (lvm_host_vars_config | default([])) +
        (lvm_playbook_config | default([]))
      | unique }}
  tags: lvm

- name: Install necessary packages
  ansible.builtin.package:
    name:
      - lvm2
      - xfsprogs
    state: present
  become: true
  tags: lvm

- name: Create volume groups
  community.general.lvg:
    vg: "{{ item.vg }}"
    pvs: "{{ item.pv }}"
    force: "{{ item.force | default(false) }}"
  loop: "{{ lvm_config }}"
  become: true
  tags: lvm

- name: Create logical volumes
  community.general.lvol:
    vg: "{{ lv.0.vg }}"
    lv: "{{ lv.1.lv }}"
    size: "{{ lv.1.size }}"
  loop: "{{ lvm_config | subelements('logical_volumes') }}"
  loop_control:
    loop_var: lv
  become: true
  tags: lvm

- name: Create filesystems
  community.general.filesystem:
    fstype: "{{ lv.1.fs_type | default('xfs') }}"
    dev: "/dev/{{ lv.0.vg }}/{{ lv.1.lv }}"
  loop: "{{ lvm_config | subelements('logical_volumes') }}"
  loop_control:
    loop_var: lv
  become: true
  tags: lvm

- name: Create data folders
  ansible.builtin.file:
    path: "{{ lv.1.mount }}"
    state: directory
    mode: "0755"
  loop: "{{ lvm_config | subelements('logical_volumes') }}"
  loop_control:
    loop_var: lv
  become: true
  tags: lvm

- name: Mount the volumes
  ansible.posix.mount:
    path: "{{ lv.1.mount }}"
    src: "/dev/{{ lv.0.vg }}/{{ lv.1.lv }}"
    fstype: "{{ lv.1.fs_type | default('xfs') }}"
    opts: "{{ lv.1.opts | default('defaults') }}"
    state: mounted
  loop: "{{ lvm_config | subelements('logical_volumes') }}"
  loop_control:
    loop_var: lv
  notify: Reload systemd
  become: true
  tags: lvm
