repository: ansible-roles/borgbackup/vars/main.yml

# Variables for BorgBackup Ansible Role

# Define the backup repository location
backup_repository: "/path/to/backup/repo"

# Define the retention policy for backups
retention_policy:
  daily: 7
  weekly: 4
  monthly: 12

# Define the Borg encryption key
encryption_key: "your-encryption-key"

# Define the Borg compression method
compression: "lz4"

# Define the list of files or directories to backup
files_to_backup:
  - "/home/user/data"
  - "/etc/config"

# Define the Borg prune options
prune_options: "--keep-daily=7 --keep-weekly=4 --keep-monthly=12"