---
name: Ansible Collection Lint & Syntax Check

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ansible-lint:
    name: Lint and Validate Collection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ansible-core and linters
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core ansible-lint yamllint

      - name: Install collection dependencies (optional)
        run: |
          if [ -f requirements.yml ]; then
            ansible-galaxy collection install -r requirements.yml
          fi

      - name: Run YAML Lint
        run: |
          yamllint .

      - name: Run Ansible Lint
        run: |
          ansible-lint .

      - name: Validate Ansible Collection Structure
        run: |
          ansible-galaxy collection build --force
